spring:
  datasource:
    url: jdbc:h2:mem:crypto
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  api-docs:
    path: /api-docs

files:
  input: "classpath:input"

